# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Planning sub-agent for creating execution plans."""

import json
import os
from datetime import datetime
from pathlib import Path

from google.adk import Agent
from google.adk.agents.callback_context import CallbackContext
from google.genai import types
from ..config.safety import SAFETY_SETTINGS_RELAXED


async def save_plan_as_artifact(
    plan_id: str,
    client_request: str,
    plan_content: str,
    output_dir: str = "secure_mediation_agent/artifacts/plans",
    tool_context=None,  # ADKが自動的に注入
) -> str:
    """Save execution plan as a markdown artifact.

    Args:
        plan_id: Base identifier for the plan (e.g., "okinawa-trip").
        client_request: Original client request.
        plan_content: The plan content in markdown format.
        output_dir: Directory to save the plan artifact (relative to project root).

    Returns:
        Path to the saved plan file and the unique plan_id with timestamp.
    """
    # Convert to absolute path relative to project root
    if not os.path.isabs(output_dir):
        # Get the project root directory (parent of secure_mediation_agent)
        current_dir = Path(__file__).parent.parent.parent
        output_dir = current_dir / output_dir
    else:
        output_dir = Path(output_dir)

    # Create output directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate unique plan_id with timestamp (HHMM) to prevent collisions
    timestamp_hhmm = datetime.now().strftime("%H%M")
    timestamp_full = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Append time to plan_id if not already included
    if not any(char.isdigit() and len(plan_id.split('-')[-1]) == 4 for char in plan_id[-4:]):
        unique_plan_id = f"{plan_id}-{timestamp_hhmm}"
    else:
        unique_plan_id = plan_id

    filename = f"{unique_plan_id}_{timestamp_full}.md"
    filepath = output_dir / filename

    # Create markdown document with unique plan_id
    markdown_content = f"""# Execution Plan: {unique_plan_id}

**Created:** {datetime.now().isoformat()}

## Client Request
{client_request}

## Execution Plan
{plan_content}

---
*This plan was generated by the Secure Mediation Agent Planning Sub-agent*
"""

    # Save to file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(markdown_content)

    # セッション状態を更新（承認フラグ管理）
    if tool_context:
        count = tool_context.state.get('plan_generation_count', 0)
        tool_context.state['plan_generation_count'] = count + 1
        tool_context.state['plan_approved'] = False  # 新しい計画は再承認が必要
        tool_context.state['plan_change_approved'] = False

    # Return JSON with both file path and unique plan_id for downstream use
    import json
    return json.dumps({
        "file_path": str(filepath),
        "plan_id": unique_plan_id,
        "original_plan_id": plan_id,
        "message": f"Plan saved successfully. Use plan_id '{unique_plan_id}' for all subsequent operations.",
        "approval_required": True,
        "approval_message": "⚠️ この計画はユーザーの承認が必要です。計画内容をユーザーに提示し、承認を得てからorchestratorに委任してください。"
    }, ensure_ascii=False)


async def create_structured_plan(
    client_request: str,
    matched_agents: list[dict],
) -> str:
    """Create a structured execution plan in JSON format.

    Args:
        client_request: The client's original request.
        matched_agents: List of matched agent information.

    Returns:
        JSON string containing the structured plan.
    """
    # This is a helper function that will be called by the agent
    # The actual plan creation logic will be done by the LLM
    plan = {
        "plan_id": f"plan_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
        "client_request": client_request,
        "steps": [],
        "status": "draft",
        "created_at": datetime.now().isoformat(),
    }

    return json.dumps(plan, indent=2, ensure_ascii=False)


async def planner_change_approval_gate(
    callback_context: CallbackContext,
) -> types.Content | None:
    """planner起動前にplan_change_approvedフラグを確認するbefore_agent_callback。

    2回目以降の計画生成（計画変更）時に、ユーザーの承認がなければブロックする。
    初回の計画生成（plan_generation_count == 0）はブロックしない。
    """
    state = callback_context.state
    plan_count = state.get('plan_generation_count', 0)
    if plan_count > 0 and not state.get('plan_change_approved', False):
        return types.Content(
            role="model",
            parts=[types.Part(text=(
                "⚠️ 計画の変更にはユーザーの承認が必要です。"
                "計画を変更する理由をユーザーに説明し、承認を得てから"
                "plannerに再委任してください。"
            ))]
        )
    return None


planner = Agent(
    model='gemini-2.5-pro',
    name='planner',
    description=(
        'Planning sub-agent that analyzes client requests and creates '
        'step-by-step execution plans using matched agents.'
    ),
    instruction="""
You are a planning specialist in a secure AI agent mediation platform.

**IMPORTANT: Always respond in Japanese (日本語) to the user.**

Your responsibilities:
1. **Analyze Client Requests**: Carefully understand what the client wants to achieve
2. **Design Execution Plans**: Create detailed, step-by-step plans that utilize the matched agents
3. **Ensure Security**: Consider security implications at each step
4. **Collaborate**: Work with the client and matched agents to refine the plan
5. **Save as Artifact**: Store the final plan as a markdown artifact for reference

When creating a plan:
- Break down complex requests into atomic, manageable steps
- Specify which agent should handle each step
- Define clear inputs and expected outputs for each step
- Identify dependencies between steps
- Consider error handling and fallback strategies

**CRITICAL: What to include and exclude in plans**

✅ INCLUDE ONLY external A2A agents (agents that perform actual tasks):
- airline_agent (フライト検索・予約)
- hotel_agent (ホテル検索・予約)
- car_rental_agent (レンタカー検索・予約)
- local_tour_agent (現地ツアー検索・予約)
- Other matched external agents from the Agent Store

❌ DO NOT INCLUDE internal sub-agents or system agents:
- secure_mediator (root agent - handles orchestration automatically)
- final_anomaly_detector (security verification - called by root agent)
- anomaly_detector (real-time monitoring - runs automatically via callback)
- orchestrator (executes the plan - NOT a step in the plan)
- planner (that's you - NOT a step in the plan)
- matcher (agent discovery - already completed before planning)

The plan should contain ONLY the steps that orchestrator will execute by calling
external A2A agents. Security verification and final reporting are handled
automatically by the root agent AFTER orchestrator completes all plan steps.

Example of CORRECT plan:
- Step 1: airline_agent - フライト検索
- Step 2: hotel_agent - ホテル検索
- Step 3: car_rental_agent - レンタカー検索
- Step 4: local_tour_agent - ツアー検索
- Step 5: 結果集約（orchestratorが内部で実行）

Example of WRONG plan (DO NOT do this):
- Step 1-4: 外部エージェント呼び出し
- Step 5: final_anomaly_detector による検証 ← これは計画に含めない！
- Step 6: secure_mediator による最終報告 ← これも計画に含めない！

**Plan ID Format**
Generate a descriptive plan_id based on the request content and date.
Format: `<description>-<YYYYMMDD>` (e.g., `okinawa-trip-20251220`)
Note: The system will automatically append the current time (HHMM) to ensure uniqueness.

Output Format:
Your plan should be in markdown format with:
- Clear step numbering
- Agent assignment for each step
- Input/output specifications
- Dependencies
- Expected outcomes

Example Plan Structure:
## Step 1: [Task Description]
**Agent:** [agent_name]
**Input:** [input description]
**Expected Output:** [output description]
**Dependencies:** [list of prior steps]

## Step 2: [Task Description]
...

After creating the plan, use the save_plan_as_artifact tool to save it.
計画を保存した後は、計画の概要をユーザーに報告してください。
orchestratorの実行を提案しないでください（承認フローはroot agentが管理します）。

**重要: 計画の保存と報告が完了したら、必ず transfer_to_agent(agent_name='secure_mediator') を呼び出して、
ルートエージェントに制御を返してください。** これにより、ユーザーの承認フローが正しく処理されます。
""",
    before_agent_callback=planner_change_approval_gate,
    tools=[
        save_plan_as_artifact,
        create_structured_plan,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.3,  # Lower temperature for more consistent planning
        safety_settings=SAFETY_SETTINGS_RELAXED,
    ),
)
